# Generated by Django 5.0.6 on 2024-12-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('optiona', models.CharField(max_length=200)),
                ('optionb', models.CharField(max_length=200)),
                ('optionc', models.CharField(max_length=200)),
                ('optiond', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.IntegerField(default=0)),
                ('incorrect', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('user_answer', models.JSONField(default=dict)),
                ('answered_questions', models.ManyToManyField(blank=True, related_name='answered_questions', to='quiz_app.questionset')),
                ('quetions', models.ManyToManyField(to='quiz_app.questionset')),
            ],
        ),
    ]
