# Generated by Django 5.0.6 on 2024-12-14 08:49

from django.db import migrations

def populate_questions(apps, schema_editor):
    QuestionSet = apps.get_model('quiz_app', 'QuestionSet')
    questions = [
        {
            "question": "What is the capital of France?",
            "optiona": "Madrid",
            "optionb": "Paris",
            "optionc": "Berlin",
            "optiond": "Rome",
            "answer": "Paris"
        },
        {
            "question": "Which planet is known as the Red Planet?",
            "optiona": "Jupiter",
            "optionb": "Earth",
            "optionc": "Venus",
            "optiond": "Mars",
            "answer": "Mars"
        },
        {
            "question": "What is the largest mammal?",
            "optiona": "Giraffe",
            "optionb": "Elephant",
            "optionc": "Great White Shark",
            "optiond": "Blue Whale",
            "answer": "Blue Whale"
        },
        {
            "question": "Who wrote 'Romeo and Juliet'?",
            "optiona": "Jane Austen",
            "optionb": "Charles Dickens",
            "optionc": "William Shakespeare",
            "optiond": "Mark Twain",
            "answer": "William Shakespeare"
        },
        {
            "question": "What is the square root of 64?",
            "optiona": "7",
            "optionb": "6",
            "optionc": "8",
            "optiond": "9",
            "answer": "8"
        },
        {
            "question": "What is the chemical symbol for water?",
            "optiona": "HO",
            "optionb": "O2",
            "optionc": "CO2",
            "optiond": "H2O",
            "answer": "H2O"
        },
        {
            "question": "Which continent is known as the 'Dark Continent'?",
            "optiona": "Australia",
            "optionb": "Asia",
            "optionc": "South America",
            "optiond": "Africa",
            "answer": "Africa"
        },
        {
            "question": "Who discovered penicillin?",
            "optiona": "Isaac Newton",
            "optionb": "Marie Curie",
            "optionc": "Alexander Fleming",
            "optiond": "Albert Einstein",
            "answer": "Alexander Fleming"
        },
        {
            "question": "What is the speed of light?",
            "optiona": "300,000 km/s",
            "optionb": "150,000 km/s",
            "optionc": "1,080,000 km/h",
            "optiond": "750,000 km/h",
            "answer": "300,000 km/s"
        },
        {
            "question": "Which gas do plants primarily use for photosynthesis?",
            "optiona": "Oxygen",
            "optionb": "Carbon Dioxide",
            "optionc": "Nitrogen",
            "optiond": "Hydrogen",
            "answer": "Carbon Dioxide"
        },
        {
            "question": "Who painted the Mona Lisa?",
            "optiona": "Leonardo da Vinci",
            "optionb": "Vincent van Gogh",
            "optionc": "Pablo Picasso",
            "optiond": "Claude Monet",
            "answer": "Leonardo da Vinci"
        },
        {
            "question": "Which country is known as the Land of the Rising Sun?",
            "optiona": "India",
            "optionb": "Japan",
            "optionc": "China",
            "optiond": "South Korea",
            "answer": "Japan"
        },
        {
            "question": "What is the boiling point of water at sea level?",
            "optiona": "100°C",
            "optionb": "90°C",
            "optionc": "120°C",
            "optiond": "80°C",
            "answer": "100°C"
        },
        {
            "question": "What is the main ingredient in guacamole?",
            "optiona": "Lime",
            "optionb": "Tomato",
            "optionc": "Onion",
            "optiond": "Avocado",
            "answer": "Avocado"
        },
        {
            "question": "What is the smallest unit of life?",
            "optiona": "Cell",
            "optionb": "Atom",
            "optionc": "Molecule",
            "optiond": "Tissue",
            "answer": "Cell"
        },
    ]

    for q in questions:
        QuestionSet.objects.create(**q)





class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_questions)
    ]

