# Generated by Django 5.0.6 on 2024-12-13 16:54

from django.db import migrations
def populate_questions(apps, schema_editor):
    QuestionSet = apps.get_model('quiz_app', 'QuestionSet')
    questions = [
        {
            "question": "What is the capital of France?",
            "optiona": "Berlin",
            "optionb": "Madrid",
            "optionc": "Paris",
            "optiond": "Rome",
            "answer": "Option C"
        },
        {
            "question": "Which planet is known as the Red Planet?",
            "optiona": "Earth",
            "optionb": "Mars",
            "optionc": "Venus",
            "optiond": "Jupiter",
            "answer": "Option B"
        },
        {
            "question": "What is the largest mammal?",
            "optiona": "Elephant",
            "optionb": "Blue Whale",
            "optionc": "Great White Shark",
            "optiond": "Giraffe",
            "answer": "Option B"
        },
        {
            "question": "Who wrote 'Romeo and Juliet'?",
            "optiona": "Charles Dickens",
            "optionb": "Jane Austen",
            "optionc": "William Shakespeare",
            "optiond": "Mark Twain",
            "answer": "Option C"
        },
        {
            "question": "What is the square root of 64?",
            "optiona": "6",
            "optionb": "7",
            "optionc": "8",
            "optiond": "9",
            "answer": "Option C"
        },
        {
            "question": "What is the chemical symbol for water?",
            "optiona": "O2",
            "optionb": "H2O",
            "optionc": "CO2",
            "optiond": "HO",
            "answer": "Option B"
        },
        {
            "question": "Which continent is known as the 'Dark Continent'?",
            "optiona": "Asia",
            "optionb": "South America",
            "optionc": "Africa",
            "optiond": "Australia",
            "answer": "Option C"
        },
        {
            "question": "Who discovered penicillin?",
            "optiona": "Marie Curie",
            "optionb": "Alexander Fleming",
            "optionc": "Isaac Newton",
            "optiond": "Albert Einstein",
            "answer": "Option B"
        },
        {
            "question": "What is the speed of light?",
            "optiona": "300,000 km/s",
            "optionb": "150,000 km/s",
            "optionc": "1,080,000 km/h",
            "optiond": "750,000 km/h",
            "answer": "Option A"
        },
        {
            "question": "Which gas do plants primarily use for photosynthesis?",
            "optiona": "Oxygen",
            "optionb": "Carbon Dioxide",
            "optionc": "Nitrogen",
            "optiond": "Hydrogen",
            "answer": "Option B"
        },
        {
            "question": "Who painted the Mona Lisa?",
            "optiona": "Vincent van Gogh",
            "optionb": "Pablo Picasso",
            "optionc": "Leonardo da Vinci",
            "optiond": "Claude Monet",
            "answer": "Option C"
        },
        {
            "question": "Which country is known as the Land of the Rising Sun?",
            "optiona": "India",
            "optionb": "Japan",
            "optionc": "China",
            "optiond": "South Korea",
            "answer": "Option B"
        },
        {
            "question": "What is the boiling point of water at sea level?",
            "optiona": "90°C",
            "optionb": "100°C",
            "optionc": "120°C",
            "optiond": "80°C",
            "answer": "Option B"
        },
        {
            "question": "What is the main ingredient in guacamole?",
            "optiona": "Tomato",
            "optionb": "Avocado",
            "optionc": "Onion",
            "optiond": "Lime",
            "answer": "Option B"
        },
        {
            "question": "What is the smallest unit of life?",
            "optiona": "Atom",
            "optionb": "Cell",
            "optionc": "Molecule",
            "optiond": "Tissue",
            "answer": "Option B"
        },
    ]

    for q in questions:
        QuestionSet.objects.create(**q)



class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_auto_20241213_2219'),
    ]

    operations = [
        migrations.RunPython(populate_questions)
    ]
