# Generated by Django 5.0.6 on 2024-12-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_auto_20241213_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='answered_questions',
            field=models.ManyToManyField(blank=True, related_name='answered_questions', to='quiz_app.questionset'),
        ),
        migrations.DeleteModel(
            name='UserAnswers',
        ),
    ]
